In [1]:
import pandas as pd
df=pd.read_csv("fdny-firehouse-listing.csv")
print(df.columns)

Index(['FacilityName', 'FacilityAddress', 'Borough', 'Postcode', 'Latitude',
       'Longitude', 'Community Board', 'Community Council ', 'Census Tract',
       'BIN', 'BBL', 'NTA'],
      dtype='object')

In [3]:
df

,FacilityName,FacilityAddress,Borough,Postcode,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,Engine 4/Ladder 15,42 South Street,Manhattan,10005.0,40.703466,-74.007538,1.0,1.0,7.0,1000867.0,1.000350e+09,Battery Park City-Lower Manhattan ...
1,Engine 10/Ladder 10,124 Liberty Street,Manhattan,10006.0,40.710072,-74.012523,1.0,1.0,13.0,1075700.0,1.000520e+09,Battery Park City-Lower Manhattan ...
2,Engine 6,49 Beekman Street,Manhattan,10038.0,40.710048,-74.005245,1.0,1.0,1501.0,1001287.0,1.000930e+09,Battery Park City-Lower Manhattan ...
3,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan,10007.0,40.715463,-74.005938,1.0,1.0,33.0,1001647.0,1.001500e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
4,Ladder 8,14 North Moore Street,Manhattan,10013.0,40.719759,-74.006678,1.0,1.0,33.0,1002150.0,1.001890e+09,SoHo-TriBeCa-Civic Center-Little Italy ...
...,...,...,...,...,...,...,...,...,...,...,...,...
213,Engine 162/Ladder 82/Battalion 23,256 Nelson Avenue,Staten Island,10308.0,40.543205,-74.147097,3.0,51.0,15601.0,5067428.0,5.052710e+09,Great Kills ...
214,Engine 167/Ladder 87,345 Annadale Road,Staten Island,10312.0,40.554174,-74.175809,3.0,51.0,17012.0,5075428.0,5.056420e+09,Annadale-Huguenot-Prince's Bay-Eltingville ...
215,Engine 164/Ladder 84,1560 Drumgoole Road West,Staten Island,10312.0,40.535332,-74.195611,3.0,51.0,20804.0,5083491.0,5.068280e+09,Rossville-Woodrow ...
216,Engine 168/EMS Station 23,1100 Rossville Avenue,Staten Island,10309.0,40.553977,-74.212812,3.0,51.0,20801.0,5154879.0,5.070670e+09,Rossville-Woodrow ...
217,Engine 151/Ladder 76,7219 Amboy Road,Staten Island,10307.0,40.512518,-74.238822,3.0,51.0,248.0,5089056.0,5.080400e+09,Charleston-Richmond Valley-Tottenville ...

In [4]:
df.groupby('FacilityName')

In [5]:
df2=df.groupby('FacilityName')

In [6]:
df2